services:
  - type: web
    name: portfolio-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn website.wsgi:application
    pythonVersion: 3.8.0
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
