services:
  - type: web
    name: portfolio-website
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn website.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: website.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
