services:
  - type: web
    name: harsh-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn website.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: website.settings
