services:
  - type: web
    name: portfolio-website
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn website.wsgi:application
    staticPublishPath: portfolio/staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: website.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
