# Generated by Django 4.2.21 on 2025-07-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
